### ISSUE TITLE
Add method of getting client IP address

### ISSUE THREAD

**Issue by mortenn** [Kruithne/KrameWork7#67]
If the server is behind a reverse proxy, the REMOTE_ADDR value will be wrong.
Most proxies add a X-Forwarded-For header with the client address.
If the request goes through multiple proxies, this will be a comma separated list of IPs.

**Comment by KalleZ** [comment]
I noticed the same thing and submitted a somewhat solution for the reCAPTCHA part in:
https://github.com/Kruithne/KrameWork7/issues/82
