### ISSUE TITLE
Database System

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/KrameWork7#8]
KW5 contained an extensive suite of database utility classes. These should be ported over to KW7.

- Automatic schema manager.
- Query builders.
- Database connection wrappers.

**Comment by mortenn** [comment]
I'll probably update these to support mssql eventually, as I am using that on my current project.

**Comment by Kruithne** [comment]
@mortenn Since you've been working on the database stuff, I'll assign this issue to you once you've accepted the collaboration invite.

**Comment by mortenn** [comment]
The database connection wrappers part has landed. The first two features in the list still need to be worked on.

**Comment by mortenn** [comment]
All three parts have landed, so I am closing this issue now. \o/
