### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/KrameWork7#87]
Latest PR by @KalleZ fails a number of tests. These issues were not collected during merge due to Travis failures which have now been corrected.

https://travis-ci.org/Kruithne/KrameWork7/builds/273346155

**Comment by KalleZ** [comment]
I can take a look, but I'm first back at my setup Monday

**Comment by Kruithne** [comment]
Fixed by @mortenn, thanks.
